/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekt7;

import java.sql.*; 
import java.sql.DriverManager; 
import java.sql.PreparedStatement; 
import java.sql.ResultSet; 
import javax.swing.*; 
import javax.swing.table.DefaultTableModel; 
import java.sql.Connection; 
import java.util.ArrayList;
import java.util.Vector; 
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
public class Pedagoget extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement ps;
    ResultSet rs;
    int q,i,id,deleteItem;
    public Pedagoget() {
        initComponents();
        String url ="jdbc:mysql://localhost:3308/sistemet"; 
        String password = "cimcakez1";  
        String username = "root"; 
        try{
            
            conn = DriverManager.getConnection(url,username,password); 
        }catch(Exception ex){
            System.out.println("Error "+ ex.getMessage());
        
        }
        shfaqtabelen();
    }
    public void shfaqtabelen(){
    String sql="SELECT * FROM pedagoget"; 
        try{
            PreparedStatement pst=conn.prepareStatement(sql);
            rs = pst.executeQuery(); 
            DefaultTableModel model= (DefaultTableModel) Tabel1.getModel();
                    
            while (rs.next()) {  
                model.addRow(new String[]{
                    rs.getString(1), 
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),});
            }
         
        }catch(Exception ex){
            System.out.println("Error : "+ ex.getMessage());
        }
         
        }
        public void Update()  
        {
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                conn= DriverManager.getConnection("jdbc:mysql://localhost:3308/sistemet","root","cimcakez1");
                ps=conn.prepareStatement("select * from pedagoget");
                
                rs=ps.executeQuery();
                ResultSetMetaData stData = rs.getMetaData();
                
                q= stData.getColumnCount();
                
                DefaultTableModel RecordTable=(DefaultTableModel)Tabel1.getModel();
                RecordTable.setRowCount(0);
                
                while(rs.next()){
                    Vector columnData=new Vector();
                    
                    for(i= 1;i<=q;i++) 
                    {
                        columnData.add(rs.getString("id"));
                        columnData.add(rs.getString("emri"));
                        columnData.add(rs.getString("mbiemri"));
                        columnData.add(rs.getString("dega"));
                        columnData.add(rs.getString("grada"));
                        
                    }
                    RecordTable.addRow(columnData);
                }
                
            }catch(Exception ex){
                
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Text1 = new javax.swing.JTextField();
        Text2 = new javax.swing.JTextField();
        Text3 = new javax.swing.JTextField();
        Text4 = new javax.swing.JTextField();
        Text5 = new javax.swing.JTextField();
        Shto = new javax.swing.JButton();
        Edito = new javax.swing.JButton();
        Pastro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Text6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Id:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Emri:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mbiemri:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Dega:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Grada:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Pedagoget");

        Text1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Text2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Text3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Text4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text4ActionPerformed(evt);
            }
        });

        Text5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Shto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Shto.setText("Shto Pedagog");
        Shto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShtoActionPerformed(evt);
            }
        });

        Edito.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Edito.setText("Edito");
        Edito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditoActionPerformed(evt);
            }
        });

        Pastro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Pastro.setText("Pastro");
        Pastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PastroActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Kerko:");

        Text6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Text6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Text6KeyReleased(evt);
            }
        });

        Tabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Emri", "Mbiemri", "Dega", "Grada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Text2)
                    .addComponent(Text3)
                    .addComponent(Text1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Shto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Edito, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Pastro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Text5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addComponent(Text4, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(Text4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Shto)
                    .addComponent(Edito)
                    .addComponent(Pastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Text6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Text4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text4ActionPerformed

    private void ShtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShtoActionPerformed
        try{  
           
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/sistemet","root","cimcakez1");
            ps=conn.prepareStatement("insert into pedagoget values(?,?,?,?,?)");
            ps.setInt(1,Integer.parseInt(Text1.getText())); 
            ps.setString(2,Text2.getText());
            ps.setString(3,Text3.getText());
            ps.setString(4,Text4.getText());
            ps.setString(5,Text5.getText());
            ps.execute();
            Update();
        }catch (Exception ex){
             System.out.println("Error "+ ex.getMessage());
          }
    }//GEN-LAST:event_ShtoActionPerformed

    private void PastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PastroActionPerformed
         Text1.setText("");
         Text2.setText("");
         Text3.setText("");
         Text4.setText("");
         Text5.setText("");
    }//GEN-LAST:event_PastroActionPerformed

    private void Text6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text6KeyReleased
        DefaultTableModel table= (DefaultTableModel)Tabel1.getModel();
        String search=Text6.getText().toUpperCase();
        TableRowSorter<DefaultTableModel> s = new TableRowSorter<DefaultTableModel>(table);
        Tabel1.setRowSorter(s);
        
        s.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_Text6KeyReleased

    private void EditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditoActionPerformed
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/sistemet","root","cimcakez1");
            ps=conn.prepareStatement("update pedagoget set emri=?,mbiemri=?,dega=?,grada=? where id=?");
            ps.setString(5,Text1.getText());
            ps.setString(1,Text2.getText());
            ps.setString(2,Text3.getText());
            ps.setString(3,Text4.getText());
            ps.setString(4,Text5.getText());

            ps.execute();
            Update();
        }catch (Exception ex){
             System.out.println("Error "+ ex.getMessage());
          }
    }//GEN-LAST:event_EditoActionPerformed

    private void Tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel1MouseClicked
        DefaultTableModel RecordTable=(DefaultTableModel)Tabel1.getModel();
      int SelectedRows=Tabel1.getSelectedRow();
      Text1.setText(RecordTable.getValueAt(SelectedRows,0).toString());
      Text2.setText(RecordTable.getValueAt(SelectedRows,1).toString());
      Text3.setText(RecordTable.getValueAt(SelectedRows,2).toString());
      Text4.setText(RecordTable.getValueAt(SelectedRows,3).toString());
      Text5.setText(RecordTable.getValueAt(SelectedRows,4).toString());
    }//GEN-LAST:event_Tabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedagoget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedagoget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedagoget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedagoget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedagoget().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edito;
    private javax.swing.JButton Pastro;
    private javax.swing.JButton Shto;
    private javax.swing.JTable Tabel1;
    private javax.swing.JTextField Text1;
    private javax.swing.JTextField Text2;
    private javax.swing.JTextField Text3;
    private javax.swing.JTextField Text4;
    private javax.swing.JTextField Text5;
    private javax.swing.JTextField Text6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
